# Site settings
title: Leggy.io Blog
email: info@leggy.io
description: > # this means to ignore newlines until "baseurl:"
  Blog for leggy.io, the simple url shortener. Check here for updates and news about leggy.io.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leggy.io" # the base hostname & protocol for your site
twitter_username: leggyapp
github_username:  husker

# Build settings
markdown: kramdown
